name: 'Install phylum latest'
description: 'Install the latest version of the phylum command-line tool'
inputs:
  phylum_username:
    description: "Phylum username"
    required: true
  phylum_password:
    description: "Phylum password"
    required: true
  phylum_vesrion:
    description: "Phylum version"
    default: '0'
    required: false

runs:
  using: "composite"
  steps:
    - name: Download latest phylum release
      shell: bash
      run: curl -Lo ~/phylum-cli-release.zip "https://github.com/phylum-dev/cli/releases/latest/download/phylum-cli-release.zip"

    - name: Download specific Phylum version
      if: ${{ inputs.phylum_version != '0' }}
      shell: bash
      run: curl -Lo ~/phylum-cli-release.zip "https://github.com/phylum-dev/cli/releases/download/${{ inputs.phylum_version }}/phylum-cli-release.zip"

    - name: Run install script
      shell: bash
      run: |
        unzip ~/phylum-cli-release.zip -d ~
        # export PATH="$PWD/phylum-cli-release:$PATH"
        export PATH="$HOME/phylum-cli-release:$PATH"
        pushd "$HOME/phylum-cli-release" || exit 11
          bash install.sh
        popd
        echo "[*] installed phylum-cli"

    - name: Setup credentials
      shell: bash
      run: |
        #TODO: update to use token
        sed -i "s/user:.*/user: ${{ inputs.phylum_username }}/" ~/.phylum/settings.yaml
        sed -i "s/pass:.*/pass: ${{ inputs.phylum_password }}/" ~/.phylum/settings.yaml
        # cat ~/.phylum/settings.yaml
        echo "[*] Configured phylum-cli with credentials"

    - name: Test phylum
      shell: bash
      run: |
        export PATH="$HOME/.phylum:$PATH"
        pushd $GITHUB_WORKSPACE || exit 1
          phylum --help
        popd

