name: 'Install phylum latest'
description: 'Install the latest version of the phylum command-line tool'
inputs:
  phylum_token:
    description: "Phylum user token"
    required: true
  phylum_version:
    description: "Phylum version"
    required: false
    default: '0'

runs:
  using: "composite"
  steps:
    - name: Download latest phylum release
      shell: bash
      run: |
        echo "[*] Downloading latest release"
        curl -Lo ~/phylum-cli-release.zip "https://github.com/phylum-dev/cli/releases/latest/download/phylum-cli-release.zip"

    - name: Download specific Phylum version
      if: ${{ inputs.phylum_version != '0' }}
      shell: bash
      run: |
        echo "[*] Downloading specific version (${{ inputs.phylum_version }})"
        curl -Lo ~/phylum-cli-release.zip "https://github.com/phylum-dev/cli/releases/download/${{ inputs.phylum_version }}/phylum-cli-release.zip"

    - name: Run install script
      shell: bash
      run: |
        unzip ~/phylum-cli-release.zip -d ~
        export PATH="$HOME/phylum-cli-release:$PATH"
        pushd "$HOME/phylum-cli-release" || exit 11
          bash install.sh
        popd
        echo "[*] installed phylum-cli"

    - name: Setup credentials
      shell: bash
      run: |
        sed -i "5 a \  offline_access: ${{ inputs.phylum_token }}" ~/.phylum/settings.yaml
        echo "[*] Configured phylum-cli with token"

    - name: Test phylum
      shell: bash
      run: |
        export PATH="$HOME/.phylum:$PATH"
        pushd $GITHUB_WORKSPACE || exit 1
          phylum --help
        popd

